plugins {
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation project(':core')
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['Assets']
        }
    }
}

application {
    mainClass = 'androidtoolkit.app.AdbToolkit'
}

jar {
    manifest {
        attributes('Main-Class': application.mainClass.get())
    }
    dependsOn ':core:jar'
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
